<?php

return [

    [
        'menu_name'   => '跨境平台',
        'menu_key'    => 'saler_tools_admin',
        'menu_type'   => 0,
        'icon'        => 'nc-iconfont nc-icon-fenxiaoV6xx1',
        'api_url'     => '',
        'router_path' => '',
        'view_path'   => '',
        'methods'     => '',
        'sort'        => 100,
        'status'      => 1,
        'is_show'     => 1,
        'children'    => [
            [
                'menu_name'   => '基础数据',
                'menu_key'    => 'saler_tools_admin_goods_base_lists',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/goods_base/lists',
                'router_path' => 'saler_tools/admin/goods_base/lists',
                'view_path'   => 'admin/goods_base/lists',
                'methods'     => 'get',
                'sort'        => 100,
                'status'      => 1,
                'is_show'     => 1,
                'children'    => []
            ],
            [
                'menu_name'   => '产品分类',
                'menu_key'    => 'saler_tools_admin_category_lists',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/category/lists',
                'router_path' => 'saler_tools/admin/category/lists',
                'view_path'   => 'admin/category/lists',
                'methods'     => 'get',
                'sort'        => 95,
                'status'      => 1,
                'is_show'     => 1,
                'children'    => []
            ],
            [
                'menu_name'   => '产品型号',
                'menu_key'    => 'saler_tools_admin_series_lists',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/model/lists',
                'router_path' => 'saler_tools/admin/model/lists',
                'view_path'   => 'admin/model/lists',
                'methods'     => 'get',
                'sort'        => 90,
                'status'      => 1,
                'is_show'     => 1,
                'children'    => []
            ],
            [
                'menu_name'   => '语言管理',
                'menu_key'    => 'saler_tools_admin_language',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/language/list',
                'router_path' => 'saler_tools/admin/language/list',
                'view_path'   => 'admin/language/list',
                'methods'     => 'get',
                'sort'        => 80,
                'status'      => 1,
                'is_show'     => 1,
                'children'    => []
            ],
            [
                'menu_name'   => '汇率管理',
                'menu_key'    => 'saler_tools_admin_exchange_rate',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/exchange_rate/lists',
                'router_path' => 'saler_tools/admin/exchange_rate/lists',
                'view_path'   => 'admin/exchange_rate/lists',
                'methods'     => 'get',
                'sort'        => 70,
                'status'      => 1,
                'is_show'     => 1,
                'children'    => []
            ],
            [
                'menu_name'   => '微页管理',
                'menu_key'    => 'saler_tools_admin_diy_lists',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/diy/list',
                'router_path' => 'saler_tools/admin/diy/list',
                'view_path'   => 'admin/diy/list',
                'methods'     => 'get',
                'sort'        => 60,
                'status'      => 1,
                'is_show'     => 1,
            ],
            [
                'menu_name'   => '页面装修',
                'menu_key'    => 'saler_tools_admin_diy_edit',
                'menu_type'   => 1,
                'icon'        => '',
                'is_show'     => 0,
                'api_url'     => 'diy/diy',
                'router_path' => 'saler_tools/admin/diy/edit',
                'view_path'   => 'admin/diy/edit',
                'methods'     => 'get',
            ],
            [
                'menu_name'   => '店铺管理',
                'menu_key'    => 'saler_tools_admin_shop',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/shop/lists',
                'router_path' => 'saler_tools/admin/shop/lists',
                'view_path'   => 'admin/shop/lists',
                'methods'     => 'get',
                'sort'        => 50,
                'status'      => 1,
                'is_show'     => 1,
            ],
            [
                'menu_name'   => '公价数据',
                'menu_key'    => 'saler_tools_admin_goods_pool',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/goods_pool/lists',
                'router_path' => 'saler_tools/admin/goods_pool/lists',
                'view_path'   => 'admin/goods_pool/lists',
                'methods'     => 'get',
                'sort'        => 49,
                'status'      => 1,
                'is_show'     => 1,
            ],
            [
                'menu_name'   => '运营国家',
                'menu_key'    => 'saler_tools_admin_country',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/country/list',
                'router_path' => 'saler_tools/admin/country/list',
                'view_path'   => 'admin/country/list',
                'methods'     => 'get',
                'sort'        => 49,
                'status'      => 1,
                'is_show'     => 1,
            ],
            [
                'menu_name'   => '付费项目',
                'menu_key'    => 'saler_tools_admin_charge',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/charge/list',
                'router_path' => 'saler_tools/admin/charge/list',
                'view_path'   => 'admin/charge/list',
                'methods'     => 'get',
                'sort'        => 45,
                'status'      => 1,
                'is_show'     => 1,
            ],
            [
                'menu_name'   => '版本发布',
                'menu_key'    => 'saler_tools_admin_version',
                'menu_type'   => 1,
                'icon'        => '',
                'api_url'     => 'saler_tools/admin/version/lists',
                'router_path' => 'saler_tools/admin/version/lists',
                'view_path'   => 'admin/version/lists',
                'methods'     => 'get',
                'sort'        => 40,
                'status'      => 1,
                'is_show'     => 1,
            ]
        ]
    ],
    [
        'menu_name'   => '鉴定估价',
        'menu_key'    => 'saler_tools_admin_identify',
        'menu_type'   => 0,
        'icon'        => 'nc-iconfont nc-icon-jinrongV6xx',
        'api_url'     => '',
        'router_path' => '',
        'view_path'   => '',
        'methods'     => '',
        'sort'        => 99,
        'status'      => 1,
        'is_show'     => 1,
        'children'    => [
            [
                'menu_name'   => '商品鉴定',
                'menu_key'    => 'saler_tools_admin_identify_goods',
                'menu_type'   => 1,
                'api_url'     => 'saler_tools/admin/identify/lists',
                'router_path' => 'saler_tools/admin/identify/lists',
                'view_path'   => 'admin/identify/goods',
                'methods'     => 'get',
                'sort'        => 100,
                'status'      => 1,
                'is_show'     => 1,
                'children'    => [

                ]
            ],
            [
                'menu_name'   => '鉴定师管理',
                'menu_key'    => 'saler_tools_admin_identify_user',
                'menu_type'   => 1,
                'api_url'     => 'saler_tools/admin/identify_user/lists',
                'router_path' => 'saler_tools/admin/identify_user/lists',
                'view_path'   => 'admin/identify/user',
                'methods'     => 'get',
                'sort'        => 99,
                'status'      => 1,
                'is_show'     => 1,
            ],
            [
                'menu_name'   => '鉴定配置',
                'menu_key'    => 'saler_tools_admin_identify_config',
                'menu_type'   => 1,
                'api_url'     => 'saler_tools/admin/identify_config/list',
                'router_path' => 'saler_tools/admin/identify_config/list',
                'view_path'   => 'admin/identify/config',
                'methods'     => 'get',
                'sort'        => 80,
                'status'      => 1,
                'is_show'     => 1,
            ],
        ]
    ],
    [
        'parent_key'  => 'setting_manage',
        'menu_name'   => '邮箱服务',
        'menu_key'    => 'saler_tools_setting_email',
        'menu_type'   => 1,
        'icon'        => '',
        'is_show'     => 1,
        'api_url'     => 'setting/email',
        'router_path' => 'saler_tools/admin/setting/email',
        'view_path'   => 'admin/setting/email',
        'methods'     => 'get',
    ],
    [
        'parent_key'  => 'setting_manage',
        'menu_name'   => '通知模板',
        'menu_key'    => 'saler_tools_notify_template',
        'menu_type'   => 1,
        'icon'        => '',
        'is_show'     => 1,
        'api_url'     => 'channel/index',
        'router_path' => 'saler_tools/admin/notify_template/lists',
        'view_path'   => 'admin/notify_template/lists',
        'methods'     => 'get',
    ],
    [
        'parent_key'  => 'setting_manage',
        'menu_name'   => '渠道配置',
        'menu_key'    => 'saler_tools_admin_setting_channel',
        'menu_type'   => 1,
        'icon'        => '',
        'is_show'     => 1,
        'api_url'     => 'setting/channel',
        'router_path' => 'saler_tools/admin/setting/channel',
        'view_path'   => 'admin/setting/channel',
        'methods'     => 'get',
    ],
    [
        'parent_key'  => 'setting_manage',
        'menu_name'   => '协议管理',
        'menu_key'    => 'saler_tools_admin_setting_agreement',
        'menu_type'   => 1,
        'icon'        => '',
        'is_show'     => 1,
        'api_url'     => 'setting/agreement',
        'router_path' => 'saler_tools/admin/setting/agreement',
        'view_path'   => 'admin/setting/agreement',
        'methods'     => 'get',
    ],
    [
        'parent_key'  => 'setting_manage',
        'menu_name'   => 'APP配置',
        'menu_key'    => 'saler_tools_admin_setting_app',
        'menu_type'   => 1,
        'icon'        => '',
        'is_show'     => 1,
        'api_url'     => 'setting/agreement',
        'router_path' => 'saler_tools/admin/setting/app',
        'view_path'   => 'admin/setting/app',
        'methods'     => 'get',
    ],
    [
        'parent_key'  => 'setting_manage',
        'menu_name'   => 'IM服务配置',
        'menu_key'    => 'saler_tools_admin_setting_im',
        'menu_type'   => 1,
        'icon'        => '',
        'is_show'     => 1,
        'api_url'     => 'setting/im',
        'router_path' => 'saler_tools/admin/setting/im',
        'view_path'   => 'admin/setting/im',
        'methods'     => 'get',
    ]
];
